### ISSUE TITLE
Compile Error on Lubuntu 16 LTS

### ISSUE THREAD

**Issue by williamkibira** [a-n-t-h-o-n-y/CPPurses#2]
Hello  , after following the  instructions in the read me , all seems fine till i run `make` which produces this huge compile error log . Is there something i might be missing to compile the code ?
`child_event.cpp:1:
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:48:39: error: ‘is_nt_cc’ was not declared in this scope
     Optional(const T& value) noexcept(is_nt_cc<T>()) {
                                       ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:48:49: error: expected primary-expression before ‘>’ token
     Optional(const T& value) noexcept(is_nt_cc<T>()) {
                                                 ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:48:51: error: expected primary-expression before ‘)’ token
     Optional(const T& value) noexcept(is_nt_cc<T>()) {
                                                   ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:56:34: error: ‘is_nt_mc’ was not declared in this scope
     Optional(T&& value) noexcept(is_nt_mc<T>()) {
                                  ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:56:44: error: expected primary-expression before ‘>’ token
     Optional(T&& value) noexcept(is_nt_mc<T>()) {
                                            ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:56:46: error: expected primary-expression before ‘)’ token
     Optional(T&& value) noexcept(is_nt_mc<T>()) {
                                              ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:66:55: error: ‘is_nt_cc’ was not declared in this scope
     Optional(bool condition, const T& value) noexcept(is_nt_cc<T>()) {
                                                       ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:66:65: error: expected primary-expression before ‘>’ token
     Optional(bool condition, const T& value) noexcept(is_nt_cc<T>()) {
                                                                 ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:66:67: error: expected primary-expression before ‘)’ token
     Optional(bool condition, const T& value) noexcept(is_nt_cc<T>()) {
                                                                   ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:78:50: error: ‘is_nt_mc’ was not declared in this scope
     Optional(bool condition, T&& value) noexcept(is_nt_mc<T>()) {
                                                  ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:78:60: error: expected primary-expression before ‘>’ token
     Optional(bool condition, T&& value) noexcept(is_nt_mc<T>()) {
                                                            ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:78:62: error: expected primary-expression before ‘)’ token
     Optional(bool condition, T&& value) noexcept(is_nt_mc<T>()) {
                                                              ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:85:26: error: ‘is_nt_d’ was not declared in this scope
     ~Optional() noexcept(is_nt_d<T>()) { this->destroy(); }
                          ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:85:35: error: expected primary-expression before ‘>’ token
     ~Optional() noexcept(is_nt_d<T>()) { this->destroy(); }
                                   ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:85:37: error: expected primary-expression before ‘)’ token
     ~Optional() noexcept(is_nt_d<T>()) { this->destroy(); }
                                     ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:93:44: error: ‘is_nt_cc’ was not declared in this scope
     Optional(const Optional& rhs) noexcept(is_nt_cc<T>()) {
                                            ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:93:54: error: expected primary-expression before ‘>’ token
     Optional(const Optional& rhs) noexcept(is_nt_cc<T>()) {
                                                      ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:93:56: error: expected primary-expression before ‘)’ token
     Optional(const Optional& rhs) noexcept(is_nt_cc<T>()) {
                                                        ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:104:39: error: ‘is_nt_mc’ was not declared in this scope
     Optional(Optional&& rhs) noexcept(is_nt_mc<T>()) {
                                       ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:104:49: error: expected primary-expression before ‘>’ token
     Optional(Optional&& rhs) noexcept(is_nt_mc<T>()) {
                                                 ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:104:51: error: expected primary-expression before ‘)’ token
     Optional(Optional&& rhs) noexcept(is_nt_mc<T>()) {
                                                   ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:144:55: error: ‘is_nt_d_cc_ca’ was not declared in this scope
     Optional& operator=(const Optional& rhs) noexcept(is_nt_d_cc_ca<T>()) {
                                                       ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:144:70: error: expected primary-expression before ‘>’ token
     Optional& operator=(const Optional& rhs) noexcept(is_nt_d_cc_ca<T>()) {
                                                                      ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:144:72: error: expected primary-expression before ‘)’ token
     Optional& operator=(const Optional& rhs) noexcept(is_nt_d_cc_ca<T>()) {
                                                                        ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:161:50: error: ‘is_nt_d_mc_ma’ was not declared in this scope
     Optional& operator=(Optional&& rhs) noexcept(is_nt_d_mc_ma<T>()) {
                                                  ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:161:65: error: expected primary-expression before ‘>’ token
     Optional& operator=(Optional&& rhs) noexcept(is_nt_d_mc_ma<T>()) {
                                                                 ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:161:67: error: expected primary-expression before ‘)’ token
     Optional& operator=(Optional&& rhs) noexcept(is_nt_d_mc_ma<T>()) {
                                                                   ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:179:58: error: ‘is_nt_d_cc_a’ was not declared in this scope
     Optional& operator=(const Optional<U>& rhs) noexcept(is_nt_d_cc_a<T, U>()) 
                                                          ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:179:72: error: expected primary-expression before ‘,’ token
    Optional& operator=(const Optional<U>& rhs) noexcept(is_nt_d_cc_a<T, U>()) {
                                                                       ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:179:72: error: expected ‘)’ before ‘,’ token
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:179:72: error: expected ‘;’ before ‘,’ token
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:196:53: error: ‘is_nt_d_mc_a’ was not declared in this scope
     Optional& operator=(Optional<U>&& rhs) noexcept(is_nt_d_mc_a<T, U>()) {
                                                     ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:196:67: error: expected primary-expression before ‘,’ token
     Optional& operator=(Optional<U>&& rhs) noexcept(is_nt_d_mc_a<T, U>()) {
                                                                   ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:196:67: error: expected ‘)’ before ‘,’ token
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:196:67: error: expected ‘;’ before ‘,’ token
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:213:50: error: ‘is_nt_d_cc_ca’ was not declared in this scope
     Optional& operator=(const T& value) noexcept(is_nt_d_cc_ca<T>()) {
                                                  ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:213:65: error: expected primary-expression before ‘>’ token
     Optional& operator=(const T& value) noexcept(is_nt_d_cc_ca<T>()) {
                                                                 ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:213:67: error: expected primary-expression before ‘)’ token
     Optional& operator=(const T& value) noexcept(is_nt_d_cc_ca<T>()) {
                                                                   ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:227:45: error: ‘is_nt_d_mc_ma’ was not declared in this scope
     Optional& operator=(T&& value) noexcept(is_nt_d_mc_ma<T>()) {
                                             ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:227:60: error: expected primary-expression before ‘>’ token
     Optional& operator=(T&& value) noexcept(is_nt_d_mc_ma<T>()) {
                                                            ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:227:62: error: expected primary-expression before ‘)’ token
     Optional& operator=(T&& value) noexcept(is_nt_d_mc_ma<T>()) {
                                                              ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:242:47: error: ‘is_nt_d’ was not declared in this scope
     Optional& operator=(opt::None_t) noexcept(is_nt_d<T>()) {
                                               ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:242:56: error: expected primary-expression before ‘>’ token
     Optional& operator=(opt::None_t) noexcept(is_nt_d<T>()) {
                                                        ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:242:58: error: expected primary-expression before ‘)’ token
     Optional& operator=(opt::None_t) noexcept(is_nt_d<T>()) {
                                                          ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:252:43: error: ‘is_nt_d_c’ was not declared in this scope
     void emplace(Args&&... args) noexcept(is_nt_d_c<T, Args...>()) {
                                           ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:252:54: error: expected primary-expression before ‘,’ token
     void emplace(Args&&... args) noexcept(is_nt_d_c<T, Args...>()) {
                                                      ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:252:54: error: expected ‘)’ before ‘,’ token
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:252:54: error: expected ‘;’ before ‘,’ token
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp: In static member function ‘static constexpr bool opt::Optional<T>::is_nt_d_cc_ca()’:
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:454:16: error: ‘conjunction’ is not a member of ‘std::experimental’
         return std::experimental::conjunction<
                ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:455:44: error: expected primary-expression before ‘,’ token
             std::is_nothrow_destructible<X>,
                                            ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:456:50: error: expected primary-expression before ‘,’ token
             std::is_nothrow_copy_constructible<X>,
                                                  ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:457:46: error: expected primary-expression before ‘>’ token
             std::is_nothrow_copy_assignable<X>>::value;
                                              ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:457:48: error: ‘::value’ has not been declared
             std::is_nothrow_copy_assignable<X>>::value;
                                                ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp: In static member function ‘static constexpr bool opt::Optional<T>::is_nt_d_mc_ma()’:
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:462:16: error: ‘conjunction’ is not a member of ‘std::experimental’
         return std::experimental::conjunction<
                ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:463:44: error: expected primary-expression before ‘,’ token
             std::is_nothrow_destructible<X>,
                                            ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:464:50: error: expected primary-expression before ‘,’ token
             std::is_nothrow_move_constructible<X>,
                                                  ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:465:46: error: expected primary-expression before ‘>’ token
             std::is_nothrow_move_assignable<X>>::value;
                                              ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:465:48: error: ‘::value’ has not been declared
             std::is_nothrow_move_assignable<X>>::value;
                                                ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp: In static member function ‘static constexpr bool opt::Optional<T>::is_nt_d_cc_a()’:
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:470:16: error: ‘conjunction’ is not a member of ‘std::experimental’
         return std::experimental::conjunction<
                ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:471:44: error: expected primary-expression before ‘,’ token
             std::is_nothrow_destructible<X>,
                                            ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:472:50: error: expected primary-expression before ‘,’ token
             std::is_nothrow_copy_constructible<X>,
                                                  ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:473:51: error: expected primary-expression before ‘>’ token
             std::is_nothrow_assignable<X, const Y&>>::value;
                                                   ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:473:53: error: ‘::value’ has not been declared
             std::is_nothrow_assignable<X, const Y&>>::value;
                                                     ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp: In static member function ‘static constexpr bool opt::Optional<T>::is_nt_d_mc_a()’:
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:478:16: error: ‘conjunction’ is not a member of ‘std::experimental’
         return std::experimental::conjunction<
                ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:479:44: error: expected primary-expression before ‘,’ token
             std::is_nothrow_destructible<X>,
                                            ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:480:50: error: expected primary-expression before ‘,’ token
             std::is_nothrow_move_constructible<X>,
                                                  ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:481:46: error: expected primary-expression before ‘>’ token
             std::is_nothrow_assignable<X, Y&&>>::value;
                                              ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:481:48: error: ‘::value’ has not been declared
             std::is_nothrow_assignable<X, Y&&>>::value;
                                                ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp: In static member function ‘static constexpr bool opt::Optional<T>::is_nt_d_c()’:
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:486:16: error: ‘conjunction’ is not a member of ‘std::experimental’
         return std::experimental::conjunction<
                ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:487:44: error: expected primary-expression before ‘,’ token
             std::is_nothrow_destructible<X>,
                                            ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:488:53: error: expected primary-expression before ‘>’ token
             std::is_nothrow_constructible<X, Args...>>::value;
                                                     ^
/home/william/Desktop/experts/ANTHONY/CPPurses/libs/Signals/libs/Optional/include/optional/optional_value.hpp:488:55: error: ‘::value’ has not been declared
             std::is_nothrow_constructible<X, Args...>>::value;
                                                       ^
In file included from /home/william/Desktop/experts/ANTHONY/CPPurses/src/system/child_event.cpp:3:0:
/home/william/Desktop/experts/ANTHONY/CPPurses/include/cppurses/widget/widget.hpp: At global scope:
/home/william/Desktop/experts/ANTHONY/CPPurses/include/cppurses/widget/widget.hpp:202:6: error: prototype for ‘decltype (u->.find_child<T>(name)) cppurses::Widget::find_child_impl(U, const string&)’ does not match any in class ‘cppurses::Widget’
 auto Widget::find_child_impl(U u, const std::string& name)
      ^
/home/william/Desktop/experts/ANTHONY/CPPurses/include/cppurses/widget/widget.hpp:152:17: error: candidate is: template<class T, class U> static decltype (u->.find_child<T>(name)) cppurses::Widget::find_child_impl(U, const string&)
     static auto find_child_impl(U u, const std::string& name)
                 ^
CMakeFiles/cppurses.dir/build.make:62: recipe for target 'CMakeFiles/cppurses.dir/src/system/child_event.cpp.o' failed
make[2]: *** [CMakeFiles/cppurses.dir/src/system/child_event.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cppurses.dir/all' failed
make[1]: *** [CMakeFiles/cppurses.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

`

**Comment by a-n-t-h-o-n-y** [comment]
Looks like the issue is coming from the Optional library using std::experimental::conjunction, which isn't supported by many compilers and is outside the C++14 specification. I'll remove this and hopefully that will get it to compile.

**Comment by williamkibira** [comment]
OK will wait for the fix , can't wait to try out your library .

**Comment by a-n-t-h-o-n-y** [comment]
Okay I think I have fixed this specific problem, if you run 
git submodule update --recursive --remote
Git will pull in the new version of the Optional library and you can attempt to recompile.
Glad you are interested :) this is my first somewhat large-scale project and it still has some holes in it.
Let me know if this fixed the issue and I'll close it.

**Comment by williamkibira** [comment]
Well, not just yet but, its a less of a large error log ,
Perhaps you could let me know what your environment has . Here is the
latest error dump on running `make`

`
In file included from
/home/william/Desktop/experts/ANTHONY/CPPurses/src/system/child_event.cpp:3:0:
/home/william/Desktop/experts/ANTHONY/CPPurses/include/cppurses/widget/widget.hpp:202:6:
error: prototype for ‘decltype (u->.find_child<T>(name))
cppurses::Widget::find_child_impl(U, const string&)’ does not match any in
class ‘cppurses::Widget’
 auto Widget::find_child_impl(U u, const std::string& name)
      ^
/home/william/Desktop/experts/ANTHONY/CPPurses/include/cppurses/widget/widget.hpp:152:17:
error: candidate is: template<class T, class U> static decltype
(u->.find_child<T>(name)) cppurses::Widget::find_child_impl(U, const
string&)
     static auto find_child_impl(U u, const std::string& name)
                 ^
CMakeFiles/cppurses.dir/build.make:62: recipe for target
'CMakeFiles/cppurses.dir/src/system/child_event.cpp.o' failed
make[2]: *** [CMakeFiles/cppurses.dir/src/system/child_event.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cppurses.dir/all'
failed
make[1]: *** [CMakeFiles/cppurses.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

`

**Comment by a-n-t-h-o-n-y** [comment]
I'm using Arch Linux 64 bit
I've tested with both GCC 7.3.0 and Clang 5.0.1

**Comment by williamkibira** [comment]
Ow , i am using Lubuntu , with GCC 5 . I could make an attempt to upgrade
my compiler if its the issue .

**Comment by a-n-t-h-o-n-y** [comment]
I just tested it on GCC 5.5.0 and it compiles, I was also able to reproduce the error on the previous commit. I'd like to have good compatability with a wide range of compilers, so I'd rather have it fixed in the project!
Hope this works for you, let me know if you can get it to compile and I'll close the issue.

**Comment by williamkibira** [comment]
Still the same error , not sure if any additional change from the last one
was made .

**Comment by a-n-t-h-o-n-y** [comment]
The latest commit(0b6f5091064fcd3e8d2352e03b75c9ef6bdfa99c) removed the function overload that was causing the error. Did you pull in new changes with `git pull --rebase` ?
Sorry if I didn't make it obvious that there was a new change.

**Comment by williamkibira** [comment]
Hehe , no its OK , so it moves on to this error block ,

Scanning dependencies of target cppurses
[  0%] Building CXX object
CMakeFiles/cppurses.dir/src/system/child_event.cpp.o
[  1%] Building CXX object
CMakeFiles/cppurses.dir/src/system/clear_screen_event.cpp.o
[  2%] Building CXX object
CMakeFiles/cppurses.dir/src/system/close_event.cpp.o
[  3%] Building CXX object
CMakeFiles/cppurses.dir/src/system/deferred_delete_event.cpp.o
[  4%] Building CXX object
CMakeFiles/cppurses.dir/src/system/disable_event.cpp.o
[  5%] Building CXX object
CMakeFiles/cppurses.dir/src/system/enable_event.cpp.o
[  7%] Building CXX object CMakeFiles/cppurses.dir/src/system/event.cpp.o
[  8%] Building CXX object
CMakeFiles/cppurses.dir/src/system/event_handler.cpp.o
[  8%] Building CXX object
CMakeFiles/cppurses.dir/src/system/event_handler_slots.cpp.o
[  9%] Building CXX object
CMakeFiles/cppurses.dir/src/system/event_invoker.cpp.o
[ 10%] Building CXX object
CMakeFiles/cppurses.dir/src/system/event_loop.cpp.o
[ 11%] Building CXX object
CMakeFiles/cppurses.dir/src/system/event_queue.cpp.o
[ 12%] Building CXX object CMakeFiles/cppurses.dir/src/system/focus.cpp.o
[ 14%] Building CXX object
CMakeFiles/cppurses.dir/src/system/focus_event.cpp.o
[ 15%] Building CXX object
CMakeFiles/cppurses.dir/src/system/hide_event.cpp.o
[ 16%] Building CXX object CMakeFiles/cppurses.dir/src/system/key.cpp.o
[ 16%] Building CXX object
CMakeFiles/cppurses.dir/src/system/key_event.cpp.o
[ 17%] Building CXX object
CMakeFiles/cppurses.dir/src/system/mouse_event.cpp.o
[ 18%] Building CXX object
CMakeFiles/cppurses.dir/src/system/move_event.cpp.o
[ 20%] Building CXX object
CMakeFiles/cppurses.dir/src/system/ncurses_event_listener.cpp.o
/home/william/Desktop/experts/ANTHONY/CPPurses/src/system/ncurses_event_listener.cpp:
In member function ‘std::unique_ptr<cppurses::Event>
cppurses::detail::NCurses_event_listener::parse_mouse_event() const’:
/home/william/Desktop/experts/ANTHONY/CPPurses/src/system/ncurses_event_listener.cpp:125:53:
error: ‘BUTTON5_PRESSED’ was not declared in this scope
     else if (static_cast<bool>(mouse_event.bstate & BUTTON5_PRESSED)) {
                                                     ^
/home/william/Desktop/experts/ANTHONY/CPPurses/src/system/ncurses_event_listener.cpp:128:55:
error: ‘BUTTON5_RELEASED’ was not declared in this scope
     } else if (static_cast<bool>(mouse_event.bstate & BUTTON5_RELEASED)) {
                                                       ^
CMakeFiles/cppurses.dir/build.make:518: recipe for target
'CMakeFiles/cppurses.dir/src/system/ncurses_event_listener.cpp.o' failed
make[2]: ***
[CMakeFiles/cppurses.dir/src/system/ncurses_event_listener.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/cppurses.dir/all'
failed
make[1]: *** [CMakeFiles/cppurses.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
william@william:~/Desktop/experts/ANTHONY/CPPurses/build$

Any chance it has to do with the version of ncurses i have or perhaps its
something else ?

**Comment by a-n-t-h-o-n-y** [comment]
Ahh, ncurse 5.x does not have BUTTON_5_* macros defined, this is for scolling up with the mouse so scrolling up will not be enabled using this version. I should have a fix out soon, thanks for sticking with me!

**Comment by a-n-t-h-o-n-y** [comment]
I have pushed a few fixes(ca7c4c0bce9491152273587409710deaba959896), tested with ncurses 5.4, this has got it to compile but there are a few issues with the older ncurses library and CPPurses.

Black and white colors are both defined to be black, it seems, as well as support for UTF-8 is missing. These two things leave the demo mostly invisible and strange characters spilling over into neighboring spots.

I'd recommend moving to the most recent version of ncurses, if you can(I am using 6.1), both the color and UTF-8 issue will take a good amount of time to work out.

**Comment by williamkibira** [comment]
Thanks for the update , and apologies for the late response . It compiles
now but, fails to link to pthread , not sure where its needed , i was
thinking of just adding the -ld to the code since i want to use it as a
library in something i am building .

At this point i think its fine to close this thread .

**Comment by a-n-t-h-o-n-y** [comment]
Forgot to mention, there is a new version of the Signals library that CPPurses is using, if you pull that in with `git submodule update --recursive --remote` and then recompile you should not need to link in pthread anymore.
I am currently looking into the color issue and the utf-8 display issues, I'll let you know if it ends up working with ncurses 5.

**Comment by a-n-t-h-o-n-y** [comment]
I've got colors working now on the newest commit to master. I don't think I'll be able to get uft-8 to work for ncurses <= 5.4, but I can fix up the border drawing to use the ncurses defined box drawing characters.

**Comment by williamkibira** [comment]
It works perfectly , compiled without a glitch , thank you very much :D

**Comment by a-n-t-h-o-n-y** [comment]
No problem, thanks for sticking with me! If you have any questions about the API or anything else, I've set up a [gitter](https://gitter.im/CPPurses/Lobby) for the project.
